
[[plugins]]
repo = 'https://github.com/ctrlpvim/ctrlp.vim'

[[plugins]]
repo = "https://github.com/mattn/ctrlp-ghq"

[[plugins]]
repo = 'https://github.com/sjl/gundo.vim'

[[plugins]]
repo = 'https://github.com/thinca/vim-quickrun'

[[plugins]]
repo = "https://github.com/sgur/ctrlp-extensions.vim"

[[plugins]]
repo = "https://github.com/tacahiroy/ctrlp-funky"

[[plugins]]
repo = "https://github.com/cocopon/colorswatch.vim"

[[plugins]]
repo = "https://github.com/rhysd/try-colorscheme.vim"

[[plugins]]
repo = 'https://github.com/mattn/benchvimrc-vim'


[[plugins]]
repo = 'https://github.com/thinca/vim-ref'

[[plugins]]
repo = 'https://github.com/tyru/open-browser.vim'
