[[plugins]]
repo = 'https://github.com/cespare/vim-toml'
on_ft = "toml"

[[plugins]]
repo = 'https://github.com/kchmck/vim-coffee-script'
on_ft = "coffee"

[[plugins]]
repo = 'https://github.com/othree/html5.vim'
on_ft = "html"

[[plugins]]
repo = 'https://github.com/hail2u/vim-css3-syntax'
on_ft = "css"

[[plugins]]
repo = 'https://github.com/othree/yajs.vim'
on_ft = "javascript"

[[plugins]]
repo = 'https://github.com/othree/es.next.syntax.vim'
on_ft = "javascript"

[[plugins]]
repo = 'https://github.com/mxw/vim-jsx'
on_ft = "javascript"

[[plugins]]
repo = 'https://github.com/zaiste/tmux.vim'
on_ft = "tmux"

[[plugins]]
repo = 'https://github.com/slim-template/vim-slim'
on_ft = "slim"

[[plugins]]
repo = 'https://github.com/tpope/vim-haml'
on_ft = "haml"

[[plugins]]
repo = 'https://github.com/vim-scripts/PKGBUILD'
on_ft = "pkgbuild"


[[plugins]]
repo = 'https://github.com/wavded/vim-stylus'
on_ft = "stylus"

[[plugins]]
repo = 'https://github.com/docker/docker'
rtp = "contrib/syntax/vim"
on_ft = "dockerfile"

[[plugins]]
repo = 'https://github.com/Shougo/unite.vim'

[[plugins]]
repo = 'https://github.com/sgur/unite-git_grep'

[[plugins]]
repo = 'https://github.com/Shougo/unite-outline'

[[plugins]]
repo = 'https://github.com/ctrlpvim/ctrlp.vim'

[[plugins]]
repo = "https://github.com/mattn/ctrlp-ghq"

[[plugins]]
repo = 'https://github.com/sjl/gundo.vim'

[[plugins]]
repo = 'https://github.com/thinca/vim-quickrun'

[[plugins]]
repo = "https://github.com/sgur/ctrlp-extensions.vim"

[[plugins]]
repo = "https://github.com/tacahiroy/ctrlp-funky"

[[plugins]]
repo = "https://github.com/cocopon/colorswatch.vim"

[[plugins]]
repo = "https://github.com/rhysd/try-colorscheme.vim"

[[plugins]]
repo = 'https://github.com/mattn/benchvimrc-vim'


[[plugins]]
repo = 'https://github.com/thinca/vim-ref'

[[plugins]]
repo = 'https://github.com/tyru/open-browser.vim'

[[plugins]]
repo = 'https://github.com/mattn/webapi-vim'
